## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file domainRadicalFunction.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_34 = Integer(34); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_36 = Integer(36); _sage_const_39 = Integer(39); _sage_const_0 = Integer(0); _sage_const_41 = Integer(41); _sage_const_1 = Integer(1); _sage_const_49 = Integer(49); _sage_const_54 = Integer(54); _sage_const_57 = Integer(57); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_59 = Integer(59); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_63 = Integer(63); _sage_const_69 = Integer(69); _sage_const_72 = Integer(72); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_74 = Integer(74); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_78 = Integer(78); _sage_const_84 = Integer(84); _sage_const_87 = Integer(87); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_19 = Integer(19); _sage_const_20 = Integer(20); _sage_const_89 = Integer(89); _sage_const_21 = Integer(21); _sage_const_22 = Integer(22)## This file (domainRadicalFunction.sagetex.sage) was *autogenerated* from domainRadicalFunction.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('domainRadicalFunction', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 a1 = ZZ.random_element(_sage_const_2 , _sage_const_10 )
except:
 _st_.goboom(_sage_const_36 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_39 
 _st_.inline(_sage_const_0 , latex(a1))
except:
 _st_.goboom(_sage_const_39 )
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.inline(_sage_const_1 , latex(a1))
except:
 _st_.goboom(_sage_const_41 )
try:
 _st_.current_tex_line = _sage_const_41 
 _st_.inline(_sage_const_2 , latex(Infinity))
except:
 _st_.goboom(_sage_const_41 )
_st_.current_tex_line = _sage_const_49 
_st_.blockbegin()
try:
 a2 = (-_sage_const_1 )**(ZZ.random_element(_sage_const_2 ))*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 b2 = (-_sage_const_1 )**(ZZ.random_element(_sage_const_2 ))*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 factor2 = a2*x + b2
 #answer2 = round(float(solve(factor2==0, x)[0].rhs()),3)
except:
 _st_.goboom(_sage_const_54 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_3 , latex(factor2))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_4 , latex(factor2))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_5 , latex(factor2))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_57 
 _st_.inline(_sage_const_6 , latex(factor2))
except:
 _st_.goboom(_sage_const_57 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_7 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_8 , latex(Infinity))
except:
 _st_.goboom(_sage_const_59 )
_st_.current_tex_line = _sage_const_63 
_st_.blockbegin()
try:
 a3 = (-_sage_const_1 )*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 b3 = (-_sage_const_1 )**(ZZ.random_element(_sage_const_2 ))*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 factor3 = a3*x + b3
 answer3 = round(float(solve(factor3==_sage_const_0 , x)[_sage_const_0 ].rhs()),_sage_const_3 )
 root3 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2 
except:
 _st_.goboom(_sage_const_69 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_9 , latex(root3))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_10 , latex(factor3))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_11 , latex(factor3))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_12 , latex(factor3))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_72 
 _st_.inline(_sage_const_13 , latex(factor3))
except:
 _st_.goboom(_sage_const_72 )
try:
 _st_.current_tex_line = _sage_const_74 
 _st_.inline(_sage_const_14 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_74 )
try:
 _st_.current_tex_line = _sage_const_74 
 _st_.inline(_sage_const_15 , latex(answer3))
except:
 _st_.goboom(_sage_const_74 )
_st_.current_tex_line = _sage_const_78 
_st_.blockbegin()
try:
 a4 = (-_sage_const_1 )*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 b4 = (-_sage_const_1 )**(ZZ.random_element(_sage_const_2 ))*(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 factor4 = a4*x + b4
 answer4 = round(float(solve(factor4==_sage_const_0 , x)[_sage_const_0 ].rhs()),_sage_const_3 )
 root4 = ZZ.random_element(_sage_const_2 ,_sage_const_5 )*_sage_const_2 +_sage_const_1 
except:
 _st_.goboom(_sage_const_84 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_16 , latex(root4))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_17 , latex(factor4))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_18 , latex(factor4))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_19 , latex(factor4))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_20 , latex(factor4))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_21 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_22 , latex(Infinity))
except:
 _st_.goboom(_sage_const_89 )
_st_.endofdoc()

