## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file leftAndRightLimits.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_48 = Integer(48); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50); _sage_const_1 = Integer(1); _sage_const_83 = Integer(83); _sage_const_2 = Integer(2); _sage_const_85 = Integer(85); _sage_const_3 = Integer(3); _sage_const_87 = Integer(87); _sage_const_4 = Integer(4); _sage_const_89 = Integer(89); _sage_const_5 = Integer(5); _sage_const_98 = Integer(98); _sage_const_6 = Integer(6); _sage_const_100 = Integer(100); _sage_const_7 = Integer(7); _sage_const_102 = Integer(102); _sage_const_8 = Integer(8); _sage_const_104 = Integer(104); _sage_const_9 = Integer(9); _sage_const_177 = Integer(177); _sage_const_10 = Integer(10); _sage_const_179 = Integer(179); _sage_const_11 = Integer(11)## This file (leftAndRightLimits.sagetex.sage) was *autogenerated* from leftAndRightLimits.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('leftAndRightLimits', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_0 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.current_tex_line = _sage_const_50 
 _st_.inline(_sage_const_1 , latex(Infinity))
except:
 _st_.goboom(_sage_const_50 )
try:
 _st_.current_tex_line = _sage_const_83 
 _st_.inline(_sage_const_2 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_83 )
try:
 _st_.current_tex_line = _sage_const_85 
 _st_.inline(_sage_const_3 , latex(Infinity))
except:
 _st_.goboom(_sage_const_85 )
try:
 _st_.current_tex_line = _sage_const_87 
 _st_.inline(_sage_const_4 , latex(_sage_const_1 ))
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_5 , latex(-_sage_const_1 ))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_98 
 _st_.inline(_sage_const_6 , latex(Infinity))
except:
 _st_.goboom(_sage_const_98 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_7 , latex(Infinity))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_8 , latex(_sage_const_1 ))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_9 , latex(_sage_const_1 ))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_177 
 _st_.inline(_sage_const_10 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_177 )
try:
 _st_.current_tex_line = _sage_const_179 
 _st_.inline(_sage_const_11 , latex(-Infinity))
except:
 _st_.goboom(_sage_const_179 )
_st_.endofdoc()

