## -*- encoding: utf-8 -*-
## This file (limitNotation.sagetex.sage) was *autogenerated* from limitNotation.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('limitNotation', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
