## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file coreModules.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (coreModules.sagetex.sage) was *autogenerated* from coreModules.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('coreModules', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()

