## -*- encoding: utf-8 -*-
## This file (modelingModules.sagetex.sage) was *autogenerated* from modelingModules.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('modelingModules', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()
