## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file constructVariationModel.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_34 = Integer(34); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_9p8 = RealNumber('9.8'); _sage_const_3 = Integer(3); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_40 = Integer(40); _sage_const_47 = Integer(47); _sage_const_0 = Integer(0); _sage_const_49 = Integer(49); _sage_const_1 = Integer(1); _sage_const_51 = Integer(51); _sage_const_61 = Integer(61); _sage_const_6 = Integer(6); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_25 = Integer(25); _sage_const_8p31 = RealNumber('8.31'); _sage_const_80 = Integer(80); _sage_const_86 = Integer(86); _sage_const_88 = Integer(88); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_90 = Integer(90); _sage_const_92 = Integer(92); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_94 = Integer(94); _sage_const_15 = Integer(15); _sage_const_98 = Integer(98); _sage_const_200 = Integer(200); _sage_const_500 = Integer(500); _sage_const_102 = Integer(102); _sage_const_104 = Integer(104); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_106 = Integer(106); _sage_const_18 = Integer(18); _sage_const_114 = Integer(114); _sage_const_0p5 = RealNumber('0.5'); _sage_const_908 = Integer(908); _sage_const_1609p34 = RealNumber('1609.34'); _sage_const_3600 = Integer(3600); _sage_const_118 = Integer(118); _sage_const_120 = Integer(120); _sage_const_19 = Integer(19); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21)## This file (constructVariationModel.sagetex.sage) was *autogenerated* from constructVariationModel.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('constructVariationModel', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_34 
_st_.blockbegin()
try:
 k = var('k')
 a = var('a')
 k1 = (_sage_const_4 *pi**_sage_const_2 ) / (_sage_const_9p8 )
 a1 = ZZ.random_element(_sage_const_3 , _sage_const_9 )
 T1 = round(k1*sqrt(a1**_sage_const_3 )*_sage_const_12 , _sage_const_2 )
except:
 _st_.goboom(_sage_const_40 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_47 
 _st_.inline(_sage_const_0 , latex(k))
except:
 _st_.goboom(_sage_const_47 )
try:
 _st_.current_tex_line = _sage_const_49 
 _st_.inline(_sage_const_1 , latex(a1))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.current_tex_line = _sage_const_49 
 _st_.inline(_sage_const_2 , latex(T1))
except:
 _st_.goboom(_sage_const_49 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_3 , latex(k1))
except:
 _st_.goboom(_sage_const_51 )
_st_.current_tex_line = _sage_const_61 
_st_.blockbegin()
try:
 P = var('P')
 V = var('V')
 n = var('n')
 R = var('R')
 T = var('T')
 temp2 = ZZ.random_element(_sage_const_1 , _sage_const_6 )*_sage_const_10 
 volume2 = ZZ.random_element(_sage_const_5 , _sage_const_25 )
 pressure2 = ZZ.random_element(_sage_const_1 , _sage_const_4 )
 R2 = _sage_const_8p31 
 #
 moles2B = round((pressure2 * volume2) / (temp2 * R2), _sage_const_3 )
 coefficientB2 = R2*temp2/volume2
 #
 temp2C = ZZ.random_element(_sage_const_1 , _sage_const_6 )*_sage_const_10 
 while temp2 == temp2C:
     temp2C = ZZ.random_element(_sage_const_1 , _sage_const_6 )*_sage_const_10 
 moles2C = round((pressure2 * volume2) / (temp2C * R2), _sage_const_3 )
 coefficientC2 = pressure2*volume2/R2
except:
 _st_.goboom(_sage_const_80 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_86 
 _st_.inline(_sage_const_4 , latex(P*V))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.current_tex_line = _sage_const_86 
 _st_.inline(_sage_const_5 , latex(n*R*T))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_6 , latex(temp2))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_7 , latex(volume2))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_8 , latex(pressure2))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_9 , latex(moles2B))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_10 , latex(coefficientB2))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_11 , latex(pressure2))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_12 , latex(volume2))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_13 , latex(temp2C))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.inline(_sage_const_14 , latex(moles2C))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_94 
 _st_.inline(_sage_const_15 , latex(coefficientC2))
except:
 _st_.goboom(_sage_const_94 )
_st_.current_tex_line = _sage_const_98 
_st_.blockbegin()
try:
 l3 = ZZ.random_element(_sage_const_2 , _sage_const_25 )
 r3 = ZZ.random_element(_sage_const_200 , _sage_const_500 )
 k3 = l3*r3/_sage_const_10 
except:
 _st_.goboom(_sage_const_102 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_16 , latex(l3))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_17 , latex(r3))
except:
 _st_.goboom(_sage_const_104 )
try:
 _st_.current_tex_line = _sage_const_106 
 _st_.inline(_sage_const_18 , latex(k3))
except:
 _st_.goboom(_sage_const_106 )
_st_.current_tex_line = _sage_const_114 
_st_.blockbegin()
try:
 tons4 = ZZ.random_element(_sage_const_1 , _sage_const_3 )
 mph4 = ZZ.random_element(_sage_const_4 , _sage_const_16 )
 energy4 = round(_sage_const_0p5  * (tons4 * _sage_const_908 ) * (mph4*_sage_const_1609p34 /_sage_const_3600 )**_sage_const_2 , _sage_const_2 )
except:
 _st_.goboom(_sage_const_118 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_19 , latex(tons4))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_20 , latex(mph4))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_21 , latex(energy4))
except:
 _st_.goboom(_sage_const_120 )
_st_.endofdoc()

