## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file identifyLinearNeed.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (identifyLinearNeed.sagetex.sage) was *autogenerated* from identifyLinearNeed.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('identifyLinearNeed', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()

