## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file identifyLinearNeed.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (identifyLinearNeed.sagetex.sage) was *autogenerated* from identifyLinearNeed.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('identifyLinearNeed', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()

