## -*- encoding: utf-8 -*-
## This file (module9ModelingObjectiveList.sagetex.sage) was *autogenerated* from module9ModelingObjectiveList.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('module9ModelingObjectiveList', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
