## -*- encoding: utf-8 -*-
## This file (constructingLogExpModel.sagetex.sage) was *autogenerated* from constructingLogExpModel.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('constructingLogExpModel', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
