## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file constructingLogExpModel.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_36 = Integer(36); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_100 = Integer(100); _sage_const_2 = Integer(2); _sage_const_44 = Integer(44); _sage_const_46 = Integer(46); _sage_const_48 = Integer(48); _sage_const_53 = Integer(53); _sage_const_1001 = Integer(1001); _sage_const_1000 = Integer(1000); _sage_const_59 = Integer(59); _sage_const_61 = Integer(61); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_63 = Integer(63); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_66 = Integer(66); _sage_const_8 = Integer(8); _sage_const_71 = Integer(71); _sage_const_0p5 = RealNumber('0.5'); _sage_const_5730 = Integer(5730); _sage_const_101 = Integer(101); _sage_const_0p01 = RealNumber('0.01'); _sage_const_79 = Integer(79); _sage_const_86 = Integer(86); _sage_const_10 = Integer(10); _sage_const_90 = Integer(90); _sage_const_11 = Integer(11); _sage_const_94 = Integer(94); _sage_const_12 = Integer(12); _sage_const_96 = Integer(96); _sage_const_13 = Integer(13)## This file (constructingLogExpModel.sagetex.sage) was *autogenerated* from constructingLogExpModel.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('constructingLogExpModel', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_36 
_st_.blockbegin()
try:
 t = var('t')
 rateList1 = ["doubles", "triples", "quadruples"]
 choose1 = ZZ.random_element(_sage_const_0 , _sage_const_3 )
 rate1 = rateList1[choose1]
 initialBacteria1 = ZZ.random_element(_sage_const_1 , _sage_const_9 )*_sage_const_100 
 k1 = ln(choose1+_sage_const_2 )
 bacteriaPopulation1 = initialBacteria1 * (choose1 + _sage_const_2 )**(t)
except:
 _st_.goboom(_sage_const_44 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_46 
 _st_.inline(_sage_const_0 , latex(rate1))
except:
 _st_.goboom(_sage_const_46 )
try:
 _st_.current_tex_line = _sage_const_46 
 _st_.inline(_sage_const_1 , latex(initialBacteria1))
except:
 _st_.goboom(_sage_const_46 )
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_2 , latex(initialBacteria1))
except:
 _st_.goboom(_sage_const_48 )
try:
 _st_.current_tex_line = _sage_const_48 
 _st_.inline(_sage_const_3 , latex(choose1+_sage_const_2 ))
except:
 _st_.goboom(_sage_const_48 )
_st_.current_tex_line = _sage_const_53 
_st_.blockbegin()
try:
 t = var('t')
 halfLifeYears2 = ZZ.random_element(_sage_const_100 , _sage_const_1001 )*ZZ.random_element(_sage_const_100 , _sage_const_1001 )
 initialAmount2 = ZZ.random_element(_sage_const_100 , _sage_const_1000 )
 k2 = -ln(_sage_const_2 )/halfLifeYears2
 equation2 = initialAmount2*e**(k2*t)
except:
 _st_.goboom(_sage_const_59 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_4 , latex(initialAmount2))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_61 
 _st_.inline(_sage_const_5 , latex(halfLifeYears2))
except:
 _st_.goboom(_sage_const_61 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_6 , latex(initialAmount2))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_7 , latex(k2))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_8 , latex(halfLifeYears2))
except:
 _st_.goboom(_sage_const_66 )
try:
 _st_.current_tex_line = _sage_const_66 
 _st_.inline(_sage_const_9 , latex(halfLifeYears2))
except:
 _st_.goboom(_sage_const_66 )
_st_.current_tex_line = _sage_const_71 
_st_.blockbegin()
try:
 t = var('t')
 r = var('r')
 k3 = ln(_sage_const_0p5 )/_sage_const_5730 
 equation3A = e**(t*k3)
 equation3B = ln(r)/k3
 percent3 = ZZ.random_element(_sage_const_1 , _sage_const_101 )
 old3 = round(equation3B(percent3*_sage_const_0p01 ), _sage_const_0 )
except:
 _st_.goboom(_sage_const_79 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_86 
 _st_.inline(_sage_const_10 , latex(k3))
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_11 , latex(_sage_const_1 /k3))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_94 
 _st_.inline(_sage_const_12 , latex(percent3))
except:
 _st_.goboom(_sage_const_94 )
try:
 _st_.current_tex_line = _sage_const_96 
 _st_.inline(_sage_const_13 , latex(old3))
except:
 _st_.goboom(_sage_const_96 )
_st_.endofdoc()

