## -*- encoding: utf-8 -*-
## This file (determineVerticalAsymptotes.sagetex.sage) was *autogenerated* from determineVerticalAsymptotes.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('determineVerticalAsymptotes', version='2019/11/14 v3.4', version_check=True)
_st_.endofdoc()
