## -*- encoding: utf-8 -*-
## This file (subgroupOfComplexNumbers.sagetex.sage) was *autogenerated* from subgroupOfComplexNumbers.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('subgroupOfComplexNumbers', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()
