## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file functionInverses.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_36 = Integer(36); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_93 = Integer(93); _sage_const_99 = Integer(99); _sage_const_103 = Integer(103); _sage_const_116 = Integer(116); _sage_const_132 = Integer(132); _sage_const_136 = Integer(136); _sage_const_4 = Integer(4); _sage_const_148 = Integer(148); _sage_const_5 = Integer(5); _sage_const_152 = Integer(152); _sage_const_6 = Integer(6); _sage_const_164 = Integer(164); _sage_const_7 = Integer(7); _sage_const_168 = Integer(168)## This file (functionInverses.sagetex.sage) was *autogenerated* from functionInverses.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('functionInverses', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_36 
_st_.blockbegin()
try:
 x = var("x")
 
 def maybeMakeNegative(natural):
     integer = natural*(-_sage_const_1 )**ZZ.random_element(_sage_const_2 )
     return integer
 
 def generateInverseLinear():
     a = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     b = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     line1 = a * x + b
     line2 = (x - b)/a
     return [line1, line2]
 
 def generateInverseSquareRoot():
     h1 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     h2 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     k = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     squareRoot = sqrt(h1*x + h2) + k
     pivot = -h2/h1
     if _sage_const_0  > (h1*(pivot - _sage_const_1 ) + h2):
         domain = [pivot, Infinity]
     else:
         domain = [-Infinity, pivot]
     squareRootInverse = ((x-k)**_sage_const_2  - h2)/h1
     return [squareRoot, squareRootInverse, domain]
 
 def generateSquared():
     h1 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     h2 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     k = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     squared = (h1*x + h2)**_sage_const_2  + k
     return squared
 
 def generateInverseCube():
     h1 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     h2 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     k = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     cube = (h1*x + h2)**_sage_const_3  + k
     cubeInverse = ((x-k)**(_sage_const_1 /_sage_const_3 ) - h2)/h1
     return [cube, cubeInverse]
 
 def generateInverseCubeRoot():
     h1 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     h2 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     k = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_8 ))
     cubeRoot = (h1*x + h2)**(_sage_const_1 /_sage_const_3 ) + k
     cubeRootInverse = ((x-k)**_sage_const_3  - h2)/h1
     return [cubeRoot, cubeRootInverse]
 #########
 f1, f1Inverse = generateInverseCube()
 f2 = generateSquared()
 f3, f3Inverse = generateInverseLinear()
 f4, f4Inverse, domain4 = generateInverseSquareRoot()
 while domain4[_sage_const_0 ] > -Infinity:
     f4, f4Inverse, domain4 = generateInverseSquareRoot()
 f5, f5Inverse = generateInverseCubeRoot()
except:
 _st_.goboom(_sage_const_93 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_99 
 _st_.inline(_sage_const_0 , latex(f1))
except:
 _st_.goboom(_sage_const_99 )
try:
 _st_.current_tex_line = _sage_const_103 
 _st_.inline(_sage_const_1 , latex(f1Inverse))
except:
 _st_.goboom(_sage_const_103 )
try:
 _st_.current_tex_line = _sage_const_116 
 _st_.inline(_sage_const_2 , latex(f2))
except:
 _st_.goboom(_sage_const_116 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_3 , latex(f3))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_136 
 _st_.inline(_sage_const_4 , latex(f3Inverse))
except:
 _st_.goboom(_sage_const_136 )
try:
 _st_.current_tex_line = _sage_const_148 
 _st_.inline(_sage_const_5 , latex(f4))
except:
 _st_.goboom(_sage_const_148 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_6 , latex(f4Inverse))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_164 
 _st_.inline(_sage_const_7 , latex(f5))
except:
 _st_.goboom(_sage_const_164 )
try:
 _st_.current_tex_line = _sage_const_168 
 _st_.inline(_sage_const_8 , latex(f5Inverse))
except:
 _st_.goboom(_sage_const_168 )
_st_.endofdoc()

