## -*- encoding: utf-8 -*-
## This file (propertiesOfLogs.sagetex.sage) was *autogenerated* from propertiesOfLogs.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('propertiesOfLogs', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
