## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file graphPolynomials.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_41 = Integer(41); _sage_const_65 = Integer(65); _sage_const_88 = Integer(88); _sage_const_63 = Integer(63); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_32 = Integer(32); _sage_const_53 = Integer(53); _sage_const_51 = Integer(51); _sage_const_76 = Integer(76); _sage_const_90 = Integer(90); _sage_const_78 = Integer(78); _sage_const_18 = Integer(18)## This file (graphPolynomials.sagetex.sage) was *autogenerated* from graphPolynomials.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('graphPolynomials', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_32 
_st_.blockbegin()
try:
 evenExp1 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2 
 evenExp2 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2 
 evenExp3 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2 
 evenExp4 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2 
 oddExp1 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2  + _sage_const_1 
 oddExp2 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2  + _sage_const_1 
 oddExp3 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2  + _sage_const_1 
 oddExp4 = ZZ.random_element(_sage_const_2 , _sage_const_5 )*_sage_const_2  + _sage_const_1 
except:
 _st_.goboom(_sage_const_41 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_0 , latex(evenExp1))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_1 , latex(oddExp1))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_2 , latex(oddExp1))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_3 , latex(oddExp1))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_4 , latex(oddExp1))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_5 , latex(evenExp2))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.inline(_sage_const_6 , latex(oddExp2))
except:
 _st_.goboom(_sage_const_63 )
try:
 _st_.current_tex_line = _sage_const_65 
 _st_.inline(_sage_const_7 , latex(oddExp2))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.current_tex_line = _sage_const_65 
 _st_.inline(_sage_const_8 , latex(oddExp2))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.current_tex_line = _sage_const_65 
 _st_.inline(_sage_const_9 , latex(oddExp2))
except:
 _st_.goboom(_sage_const_65 )
try:
 _st_.current_tex_line = _sage_const_76 
 _st_.inline(_sage_const_10 , latex(evenExp3))
except:
 _st_.goboom(_sage_const_76 )
try:
 _st_.current_tex_line = _sage_const_76 
 _st_.inline(_sage_const_11 , latex(oddExp3))
except:
 _st_.goboom(_sage_const_76 )
try:
 _st_.current_tex_line = _sage_const_78 
 _st_.inline(_sage_const_12 , latex(evenExp3))
except:
 _st_.goboom(_sage_const_78 )
try:
 _st_.current_tex_line = _sage_const_78 
 _st_.inline(_sage_const_13 , latex(evenExp3))
except:
 _st_.goboom(_sage_const_78 )
try:
 _st_.current_tex_line = _sage_const_78 
 _st_.inline(_sage_const_14 , latex(evenExp3))
except:
 _st_.goboom(_sage_const_78 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_15 , latex(evenExp4))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_88 
 _st_.inline(_sage_const_16 , latex(oddExp4))
except:
 _st_.goboom(_sage_const_88 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_17 , latex(oddExp4))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_18 , latex(oddExp4))
except:
 _st_.goboom(_sage_const_90 )
try:
 _st_.current_tex_line = _sage_const_90 
 _st_.inline(_sage_const_19 , latex(evenExp4))
except:
 _st_.goboom(_sage_const_90 )
_st_.endofdoc()

