## -*- encoding: utf-8 -*-
## This file (lowestDegreePoly.sagetex.sage) was *autogenerated* from lowestDegreePoly.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('lowestDegreePoly', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()
