## -*- encoding: utf-8 -*-
## This file (module2ObjectivesList.sagetex.sage) was *autogenerated* from module2ObjectivesList.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('module2ObjectivesList', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()
