## -*- encoding: utf-8 -*-
## This file (module2ObjectivesList.sagetex.sage) was *autogenerated* from module2ObjectivesList.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('module2ObjectivesList', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.endofdoc()
