## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file graphingQuadratics.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_112 = Integer(112); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7); _sage_const_0 = Integer(0); _sage_const_136 = Integer(136); _sage_const_139 = Integer(139); _sage_const_141 = Integer(141); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_150 = Integer(150); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_152 = Integer(152); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_161 = Integer(161); _sage_const_11 = Integer(11); _sage_const_163 = Integer(163); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_172 = Integer(172); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_17 = Integer(17); _sage_const_18 = Integer(18); _sage_const_174 = Integer(174); _sage_const_19 = Integer(19); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21)## This file (graphingQuadratics.sagetex.sage) was *autogenerated* from graphingQuadratics.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('graphingQuadratics', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_112 
_st_.blockbegin()
try:
 def maybeMakeNegative(natural):
     integer = natural*(-_sage_const_1 )**ZZ.random_element(_sage_const_2 )
     return integer
 #
 def createVertexAndEquation(direction):
     vx = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
     vy = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
     equationCoefficients = [direction, -direction*_sage_const_2 *vx, direction*(vx)**_sage_const_2  + vy]
     vertex = [vx, vy]
     extraX = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_7 ))
     extraY = equationCoefficients[_sage_const_0 ]*(extraX)**_sage_const_2  - _sage_const_2 *direction*vx*extraX + direction*(vx)**_sage_const_2 +vy
     extraPoint = [extraX, extraY]
     return [vertex, equationCoefficients, extraPoint]
 ########
 ### QUESTION 1 ###
 direction1 = _sage_const_1 
 vertex1, equationCoefficients1, extraPoint1 = createVertexAndEquation(direction1)
 ### QUESTION 2 ###
 direction2 = -_sage_const_1 
 vertex2, equationCoefficients2, extraPoint2 = createVertexAndEquation(direction2)
 ### QUESTION 3 ###
 direction3 = maybeMakeNegative(ZZ.random_element(_sage_const_2 , _sage_const_10 ))
 vertex3, equationCoefficients3, extraPoint3 = createVertexAndEquation(direction3)
except:
 _st_.goboom(_sage_const_136 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_139 
 _st_.inline(_sage_const_0 , latex(vertex1[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_139 )
try:
 _st_.current_tex_line = _sage_const_139 
 _st_.inline(_sage_const_1 , latex(vertex1[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_139 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_2 , latex(equationCoefficients1[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_3 , latex(equationCoefficients1[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_141 
 _st_.inline(_sage_const_4 , latex(equationCoefficients1[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_141 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_5 , latex(vertex1[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.inline(_sage_const_6 , latex(vertex1[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_150 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_7 , latex(equationCoefficients1[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_8 , latex(equationCoefficients1[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_152 
 _st_.inline(_sage_const_9 , latex(equationCoefficients1[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_152 )
try:
 _st_.current_tex_line = _sage_const_161 
 _st_.inline(_sage_const_10 , latex(vertex2[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_161 )
try:
 _st_.current_tex_line = _sage_const_161 
 _st_.inline(_sage_const_11 , latex(vertex2[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_161 )
try:
 _st_.current_tex_line = _sage_const_163 
 _st_.inline(_sage_const_12 , latex(equationCoefficients2[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_163 )
try:
 _st_.current_tex_line = _sage_const_163 
 _st_.inline(_sage_const_13 , latex(equationCoefficients2[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_163 )
try:
 _st_.current_tex_line = _sage_const_163 
 _st_.inline(_sage_const_14 , latex(equationCoefficients2[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_163 )
try:
 _st_.current_tex_line = _sage_const_172 
 _st_.inline(_sage_const_15 , latex(vertex3[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_172 )
try:
 _st_.current_tex_line = _sage_const_172 
 _st_.inline(_sage_const_16 , latex(vertex3[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_172 )
try:
 _st_.current_tex_line = _sage_const_172 
 _st_.inline(_sage_const_17 , latex(extraPoint3[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_172 )
try:
 _st_.current_tex_line = _sage_const_172 
 _st_.inline(_sage_const_18 , latex(extraPoint3[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_172 )
try:
 _st_.current_tex_line = _sage_const_174 
 _st_.inline(_sage_const_19 , latex(equationCoefficients3[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_174 )
try:
 _st_.current_tex_line = _sage_const_174 
 _st_.inline(_sage_const_20 , latex(equationCoefficients3[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_174 )
try:
 _st_.current_tex_line = _sage_const_174 
 _st_.inline(_sage_const_21 , latex(equationCoefficients3[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_174 )
_st_.endofdoc()

