## -*- encoding: utf-8 -*-
## This file (solvingZeroFactor.sagetex.sage) was *autogenerated* from solvingZeroFactor.tex with sagetex.sty version 2019/01/09 v3.2.
import sagetex
_st_ = sagetex.SageTeXProcessor('solvingZeroFactor', version='2019/01/09 v3.2', version_check=True)
_st_.endofdoc()
